291 make expected latency ns configurable android v2 [settings update]
mlcommons/mobile_app_open pull request #351
Opened 2022-06-08 16:22 UTC by AhmedTElthakeb

2022-06-09 00:08 UTC, anhappdev requested changes

2022-06-09 00:08 UTC, anhappdev commented on mobile_back_samsung/cpp/sbe_backend/jni/include/sbe_config.hpp
> +  src: "/sdcard/MLPerf_sideload/ic_single.nnc"
Why is the `src` updated to use local file?

2022-06-09 00:08 UTC, anhappdev commented on mobile_back_samsung/samsung_backend.mk
> +  backend_samsung_filename=libsamsungbackend
All of this was removed in `android-v2` branch because it's only used for Flutter build.

2022-06-10 15:19 UTC, anhappdev approved these changes

2022-06-13 08:14 UTC, anhappdev commented
@AhmedTElthakeb APK built from this branch with `*.so` files from `mobile_back_samsung/mobile_back_samsung/samsung/lib_060622`:
[2022-06-13_PR351_mlperf_app.apk](https://drive.google.com/file/d/1PgjbpTAuAcawWde-hOpXfTL51AborDbL/view?usp=sharing)

2022-06-14 04:30 UTC, AhmedTElthakeb commented
> @AhmedTElthakeb APK built from this branch with `*.so` files from `mobile_back_samsung/mobile_back_samsung/samsung/lib_060622`: [2022-06-13_PR351_mlperf_app.apk](https://drive.google.com/file/d/1PgjbpTAuAcawWde-hOpXfTL51AborDbL/view?usp=sharing)

Tested and seems to work fine.

2022-06-14 13:04 UTC, anhappdev commented
@AhmedTElthakeb Please resolve the conflict to merge the changes into `android-v2`.

2022-06-28 05:12 UTC, merged