Properly handle exceptions in handleResources and runBenchmarks
mlcommons/mobile_app_open pull request #414
Opened 2022-06-29 21:33 UTC by d-uzlov

Closes https://github.com/mlcommons/mobile_app_open/issues/307

If some error happens when running benchmarks application shows popup with error.
If some error happens during resource download (for example, checksum validation fails) application shows `ResourceErrorScreen` with "Clear cache" button.

<img src="https://user-images.githubusercontent.com/36223296/176548439-7d9e3af0-1f28-436c-8948-96f5a53d5a71.png" width=250><img src="https://user-images.githubusercontent.com/36223296/176548448-e9f13d1f-1b54-452e-b56b-d5b8f40d1647.png" width=250>

2022-06-30 08:41 UTC, anhappdev requested changes
On the first start after a clean install, the progress screen for loading resource did not show anymore, but only a black screen, until all the resources are downloaded.

2022-06-30 08:58 UTC, anhappdev commented
Please also add a log message in 
https://github.com/mlcommons/mobile_app_open/blob/03970131e87bab1d04ead6bad495718eb09e067e/flutter/lib/resources/file_cache_helper.dart#L46
so we can see it is still running when downloading large files, e.g.:

```dart
  Future<File> _download(String url) async {
    print('Downloading $url');
    const succesStatusCode = 200;
...
```

2022-07-01 08:11 UTC, d-uzlov commented
@anhappdev, done.

2022-07-01 10:10 UTC, anhappdev approved these changes

2022-07-01 10:31 UTC, merged