Add CI test for pixel backend
mlcommons/mobile_app_open pull request #459
Opened 2022-07-28 21:36 UTC by d-uzlov

Closes https://github.com/mlcommons/mobile_app_open/issues/457

2022-07-29 02:41 UTC, d-uzlov commented
This PR consists of 2 parts:

1. Makefile refactoring (mostly android.mk)
2. Cloudbuild config refactoring

I have created a new cloudbuild job `android-build` to replace current `Build-and-test-Flutter-Android-App-PR` one.
With this new job firebase tests run in separate jobs.

2022-07-29 11:29 UTC, anhappdev requested changes

2022-07-31 14:19 UTC, d-uzlov commented on flutter/android/android-docker.mk
> +		${proxy_docker_args} \
Done

2022-07-31 14:20 UTC, d-uzlov commented on flutter/flutter.mk
> +flutter_build_number_arg=--build-number ${FLUTTER_BUILD_NUMBER}
Done

2022-08-01 00:36 UTC, anhappdev approved these changes

2022-08-01 03:20 UTC, anhappdev requested changes
I got this error
```shell
➜ make docker/flutter/android/release
OFFICIAL_BUILD env must be explicitly set to "true" or "false"
make: *** [flutter/flutter.mk:40: flutter/check/official-build] Error 1
```

2022-08-01 07:03 UTC, d-uzlov commented
@anhappdev
Like the error says, you should set the `OFFICIAL_BUILD` env to some value to fix it.
Either as a real env or as makefile env. For example, `make docker/flutter/android/release OFFICIAL_BUILD=false`.
In the makefile there is a default value for this env, but specifically for `release` scripts there is an additional check `flutter/check/official-build` to make sure that value is set explicitly and the default is not used.

By the way, similar error will happen with the `FLUTTER_BUILD_NUMBER` env.
Both are required for `docker/flutter/android/release`, `flutter/android/release`, and `flutter/ios/release` targets.

2022-08-01 07:23 UTC, anhappdev commented
Ok. I got your point.

There is still a reference to the target `docker/flutter/android/apk` in the docs:
https://github.com/mlcommons/mobile_app_open/blob/e75502e3f04a3d08d19e3558c27043c3c7abdc29/flutter/documentation/build-and-run.md?plain=1#L53

2022-08-01 07:29 UTC, d-uzlov commented
I'll fix the documentation.

2022-08-01 08:28 UTC, anhappdev submitted a review, later dismissed

2022-08-01 15:26 UTC, anhappdev approved these changes

2022-08-01 15:40 UTC, merged