README.md per issue 11
mlcommons/mobile_app_open pull request #62
Opened 2021-09-10 18:19 UTC by relja128

Closes #11

2021-09-10 18:20 UTC, relja128 commented
I used the top half (overview) of the old readme since the full readme is in the Android folder.

2021-09-24 16:01 UTC, mcharleb requested changes

2021-09-24 16:01 UTC, mcharleb commented on README.md
> +* mobile_back_tflite - Combined TFLite / MediaTek backends for Android
We will need to add Pixel once Pixel backend is merged

2021-09-24 16:01 UTC, mcharleb commented on README.md
> +* mobile_back_tflite - Combined TFLite / MediaTek backends for Android
@relja128  I suggest we merge pixel backend first then update this PR to add Pixel and then merge this PR.

2021-09-28 05:27 UTC, stegben commented on README.md
> +* mobile_back_tflite - Combined TFLite / MediaTek backends for Android
```suggestion
* mobile_back_pixel - Pixel backend using NNAPI for Android
* mobile_back_tflite - Combined TFLite / MediaTek backends for Android
```

2021-09-28 05:43 UTC, mcharleb approved these changes

2021-09-28 05:44 UTC, merged