Update build instruction for Android with correct path
mlcommons/mobile_app_open pull request #68
Opened 2021-09-16 12:00 UTC by anhappdev

Replace `//java/org/mlperf/` with `//android/java/org/mlperf/`

2021-09-16 12:11 UTC, anhappdev commented
@relja128 The link to [MLCommons CLA](https://github.com/mlcommons/systems/blob/main/mlcommons_cla.txt) returned a `404` error. So how can I sign the MLCommons CLA?

2021-09-16 12:42 UTC, anhappdev commented
I found this page [CONTRIBUTING.md](https://github.com/mlcommons/mobile_app_open/blob/master/CONTRIBUTING.md) and already submit the linked Google form.

2021-09-20 17:14 UTC, anhappdev commented
recheck

2021-09-21 06:21 UTC, anhappdev commented
recheck

2021-09-21 06:48 UTC, mcharleb requested changes

2021-09-21 06:48 UTC, mcharleb commented on android/docs/guides/installation.md
> +we can bundle the necessary datasets directly in the app.
The license of the datasets makes that impossible

2021-09-21 06:48 UTC, mcharleb commented on android/docs/guides/installation.md
> +smaller subset of images. We recommend leaving ~300 images in
If you want a smaller set of images just use the images from performance mode. The point of the full datasets is to validate accuracy. If you don't use the full dataset, what is the point?

2021-09-21 06:48 UTC, mcharleb commented on android/docs/guides/installation.md
> +will be measured, otherwise it will only report latency results.
It will only check accuracy if submission mode is selected

2021-09-21 06:48 UTC, mcharleb commented on android/docs/guides/installation.md
> +*   Number of threads - for CPU execution
These are only applicable if the user is using a phone that uses the TFLite backend.

2021-09-24 15:57 UTC, mcharleb approved these changes

2021-09-24 15:58 UTC, merged