Enable Samsung backend for ndk 25 build
mlcommons/mobile_app_open pull request #812
Opened 2023-11-07 05:42 UTC by AhmedTElthakeb

2023-11-07 13:33 UTC, anhappdev commented
There are still some errors:

From App Build / build-android-apk:
```
Validate checksum of Samsung lib files
flutter/tool/validate-checksum.sh \
	-d mobile_back_samsung/samsung/lib \
FAIL: internal/libc++_shared.so (File not found)
	-f mobile_back_samsung/samsung/lib/checksums.txt
make: *** [flutter/android/android.mk:[31](https://github.com/mlcommons/mobile_app_open/actions/runs/6784137159/job/18440174294?pr=812#step:11:32): flutter/android/libs/checksum] Error 1
```


From Code Analysis / SonarScanner:
```
ERROR: /image-workdir/project/mobile_back_pixel/cpp/backend_tflite/BUILD:86:18: Linking mobile_back_pixel/cpp/backend_tflite/libtflitepixelbackend.so failed: (Exit 1): clang failed: error executing command (from target //mobile_back_pixel/cpp/backend_tflite:libtflitepixelbackend.so) 
  (cd /image-workdir/.cache/bazel/_bazel_root/f96fd4f8f5bca05be4940a7079fbe1d9/execroot/mlperf_app && \
  exec env - \
    PATH=/image-workdir/.cache/bazelisk/downloads/bazelbuild/bazel-6.3.2-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/android/cmdline-tools/tools/bin:/image-workdir/flutter/bin:/image-workdir/flutter/bin/cache/dart-sdk/bin:/image-workdir/.cache/.pub-cache/bin:/image-workdir/.sonar/sonar-scanner-5.0.1.3006-linux/bin:/image-workdir/.sonar/build-wrapper-linux-x86 \
    *** \
  external/androidndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang @bazel-out/arm64-v8a-opt/bin/mobile_back_pixel/cpp/backend_tflite/libtflitepixelbackend.so-2.params)
# Configuration: f70a72596caa7291b35dc91e1273c7f9c14dcfa7dd8606bbd44471844ef2ad94
# Execution platform: @local_execution_config_platform//:platform
ld.lld: error: unknown -z value: separate-code
ld.lld: error: cannot open crtbegin_so.o: No such file or directory
ld.lld: error: unable to find library -lEGL
ld.lld: error: unable to find library -lGLESv2
ld.lld: error: unable to find library -lnativewindow
ld.lld: error: unable to find library -llog
ld.lld: error: cannot open crtend_so.o: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: Elapsed time: 701.875s, Critical Path: 30.74s
INFO: 2096 processes: 281 internal, 1815 local.
FAILED: Build did NOT complete successfully
make[1]: *** [flutter/android/android.mk:40: flutter/android/libs/build] Error 1
```

2023-11-08 13:16 UTC, anhappdev commented
@AhmedTElthakeb The master branch was merged into `ndk_25_quick_hack`, and now there is a conflicting file:
`mobile_back_samsung/samsung/lib/checksums.txt`
Please resolve the conflict. If you have updated *.so files, please also provide a link to them.

2023-11-13 00:26 UTC, AhmedTElthakeb commented
> @AhmedTElthakeb The master branch was merged into `ndk_25_quick_hack`, and now there is a conflicting file: `mobile_back_samsung/samsung/lib/checksums.txt` Please resolve the conflict. If you have updated *.so files, please also provide a link to them.

I updated the checksum, should be okay to merge with Master now.

2023-11-13 15:47 UTC, anhappdev commented
@AhmedTElthakeb It looks like you didn't pull the latest `ndk_25_quick_hack`. The file `checksums.txt` is still in conflict.

2023-11-14 03:04 UTC, AhmedTElthakeb commented
> @AhmedTElthakeb The master branch was merged into `ndk_25_quick_hack`, and now there is a conflicting file: `mobile_back_samsung/samsung/lib/checksums.txt` Please resolve the conflict. If you have updated *.so files, please also provide a link to them.

Actually some .so libs got updated, so I updated the [README.md](https://github.com/mlcommons/mobile_app_open/blob/samsung_backend_for_ndk25/mobile_back_samsung/README.md) with a pointer to the new [libs](https://github.com/mlcommons/mobile_back_samsung/tree/submission_v3.1_samsung_backend_ndk25/samsung_libs).

2023-11-16 03:08 UTC, anhappdev requested changes

2023-11-16 03:08 UTC, anhappdev commented on mobile_back_samsung/samsung/lib/checksums.txt
> +f459d2b74a2330b938ea163037c5c5f896a97c1b3a7c1454051246bdab766e5c  internal/libenn_extension.so
The checksum of `internal/libenn_extension.so` in 
https://github.com/mlcommons/mobile_back_samsung/tree/submission_v3.1_samsung_backend_ndk25/samsung_libs) does not match. Please check again.

2023-11-20 10:17 UTC, merged